services:
  vision-assistant:
    build: .
    container_name: vlm_assistant
    ports:
      - "7860:7860"
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    restart: unless-stopped
